package com.example.demo.util;

public enum ElementTypeEnum {
    SOURCE_CODE,
    TEXT,
    BIG_TITLE,
    MEDIUM_TITLE,
    SMALL_TITLE,
    VERY_SMALL_TITLE,
    CONTENT,
    LIST,
    ATTACHMENT,
    HYPERLINK,
    ONE_CHOICE_QUESTION,
    MULTI_CHOICES_QUESTION,
    SHORT_TEXT_QUESTION,
    LONG_TEXT_QUESTION;
}
